'use client';

import React from 'react';

export function PullRequestsView() {
  return (
    <div className="p-4 sm:p-8">
      <h2 className="text-xl font-bold text-zinc-900 tracking-tight mb-6">AI Security Reviews</h2>
      <div className="bg-white rounded-xl border border-zinc-200 p-8 shadow-sm">
        <p className="text-zinc-600">History of AI-reviewed PRs and generated security patches.</p>
        <div className="mt-6 flex flex-col gap-4">
          <div className="p-4 border border-zinc-200 rounded-lg flex justify-between items-center">
            <div>
              <div className="font-semibold text-zinc-900">fix: patch SQL injection in payments</div>
              <div className="text-sm text-zinc-500 mt-1">Generated by FurgleAI • Merged 2 hours ago</div>
            </div>
            <span className="px-3 py-1 bg-emerald-50 text-emerald-700 rounded-full text-xs font-bold">Auto-Fixed</span>
          </div>
          <div className="p-4 border border-zinc-200 rounded-lg flex justify-between items-center">
            <div>
              <div className="font-semibold text-zinc-900">feat: add new billing endpoint</div>
              <div className="text-sm text-zinc-500 mt-1">Reviewed by FurgleAI • 1 critical finding found</div>
            </div>
            <span className="px-3 py-1 bg-red-50 text-red-700 rounded-full text-xs font-bold">Blocked</span>
          </div>
        </div>
      </div>
    </div>
  );
}
